ALTER TABLE "Materiale" ADD COLUMN IF NOT EXISTS "unitaMisura" TEXT;
ALTER TABLE "Materiale" ADD COLUMN IF NOT EXISTS "larghezza" TEXT;
ALTER TABLE "Scheda" ADD COLUMN IF NOT EXISTS "costoTaglio" DOUBLE PRECISION;
ALTER TABLE "Scheda" ADD COLUMN IF NOT EXISTS "costoCucitura" DOUBLE PRECISION;
ALTER TABLE "Scheda" ADD COLUMN IF NOT EXISTS "costoStampa" DOUBLE PRECISION;
ALTER TABLE "Scheda" ADD COLUMN IF NOT EXISTS "costoRicamo" DOUBLE PRECISION;
