-- Archivio modelli (cartamodelli) + codice modello sulle schede, con il catalogo iniziale
CREATE TABLE IF NOT EXISTS "Modello" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "codice" TEXT NOT NULL,
  "descrizione" TEXT NOT NULL,
  "categoria" TEXT NOT NULL,
  "fascia" TEXT NOT NULL,
  "note" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "Modello_codice_key" ON "Modello"("codice");
ALTER TABLE "Modello" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Scheda" ADD COLUMN IF NOT EXISTS "codiceModello" TEXT;
CREATE INDEX IF NOT EXISTS "Scheda_codiceModello_idx" ON "Scheda"("codiceModello");
INSERT INTO "Modello" ("id","codice","descrizione","categoria","fascia","updatedAt") VALUES
(gen_random_uuid()::text, 'DUSP 09', 'T-Shirt PRF', 'T-Shirt PRF', 'Uomo', now()),
(gen_random_uuid()::text, 'DUSP 19', 'T-Shirt PRF', 'T-Shirt PRF', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 013', 'T-Shirt Raglan', 'T-Shirt PRF', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 207', 'T-Shirt 3 col.', 'T-Shirt PRF', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 014', 'T-Shirt 3 col.', 'T-Shirt PRF', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 215', 'T-Shirt CLLG', 'T-Shirt PRF', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 216-V', 'T-Shirt collo V', 'T-Shirt PRF', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 011', 'T-Shirt Ws micro', 'T-Shirt WS', 'Donna', now()),
(gen_random_uuid()::text, 'DUSP 38', 'T-Shirt Ws micro', 'T-Shirt WS', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 140', 'Canotta Ws', 'T-Shirt WS', 'Donna', now()),
(gen_random_uuid()::text, 'DUSP 31', 'T-Shirt Cot', 'T-Shirt COT', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 32', 'T-Shirt Cot', 'T-Shirt COT', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 27', 'T-Shirt Hoodie', 'T-Shirt COT', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 27B', 'T-Shirt Hoodie', 'T-Shirt COT', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 139', 'Polo senza bottoni', 'Polo', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 01', 'Hoodie GM', 'Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 04', 'Hoodie GM', 'Hoodie', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 02', 'Hoodie Raglan', 'Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 03', 'Hoodie Raglan', 'Hoodie', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 136', 'Hoodie 2 col.', 'Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 137', 'Hoodie 2 col.', 'Hoodie', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP M012', 'Hoodie 3 col.', 'Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP M013', 'Hoodie 3 col.', 'Hoodie', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 206', 'Hoodie marsupio', 'Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 214', 'Hoodie SLIT', 'Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 24', 'Zip Hoodie GM', 'Zip Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 216', 'Zip Hoodie GM', 'Zip Hoodie', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 25', 'Zip Hoodie Raglan', 'Zip Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 210', 'Zip Hoodie Raglan', 'Zip Hoodie', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 26', 'Zip Hoodie 3 col.', 'Zip Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 29', 'Zip Hoodie 3 col.', 'Zip Hoodie', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 22', 'Zip Hoodie RL', 'Zip Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 28', 'Zip Hoodie CLLG', 'Zip Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 30', 'Zip Hoodie', 'Zip Hoodie', 'Donna', now()),
(gen_random_uuid()::text, 'DUSP 209', 'Zip Hoodie Three', 'Zip Hoodie', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 20', 'Sweatshirt Raglan', 'Sweatshirt', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 211', 'Sweatshirt Raglan', 'Sweatshirt', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 202', 'Sweatshirt 2 col. R-arm', 'Sweatshirt', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 203', 'Sweatshirt 2 col. R-arm', 'Sweatshirt', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 138', 'Sweatshirt Large Stripe', 'Sweatshirt', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 217', 'Sweatshirt', 'Sweatshirt', 'Donna', now()),
(gen_random_uuid()::text, 'DUSP M15', 'Sweatshirt triangolino', 'Sweatshirt', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 05', 'Sweatpants', 'Sweatpants', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 07', 'Sweatpants', 'Sweatpants', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 201', 'Sweatpants 3 col.', 'Sweatpants', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 204', 'Sweatpants 2 col.', 'Sweatpants', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 33', 'Short cotone', 'Short', 'Uomo', now()),
(gen_random_uuid()::text, 'DUSP 39', 'Short cotone', 'Short', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 08', 'Short stripe', 'Short', 'Uomo', now()),
(gen_random_uuid()::text, 'DUSP 014-S', 'Short stripe', 'Short', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 18', 'Short cotone', 'Short', 'Donna', now()),
(gen_random_uuid()::text, 'DUSP 34', 'Short DDR', 'Short', 'Donna', now()),
(gen_random_uuid()::text, 'DUSP 212', 'Short WDL', 'Short', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 213', 'Short SLIT', 'Short', 'Uomo', now()),
(gen_random_uuid()::text, 'DUSP 200', 'Short triangolo', 'Short', 'Uomo', now()),
(gen_random_uuid()::text, 'DUSP 205', 'Short triangolo', 'Short', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 13', 'Skirt', 'Skirt', 'Adulto', now()),
(gen_random_uuid()::text, 'DUSP 17', 'Skirt', 'Skirt', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 010', 'Vestitino Ws', 'Dress', 'Donna', now()),
(gen_random_uuid()::text, 'DUSP 014-D', 'Completino', 'Dress', 'Kids', now()),
(gen_random_uuid()::text, 'DUSP 208', 'Vestitino', 'Dress', 'Kids', now()),
(gen_random_uuid()::text, 'DU-P141', 'Baseline Jacket', 'Jacket', 'Uomo', now())
ON CONFLICT ("codice") DO NOTHING;
